In [2]:
import numpy as np

a = np.random.randn(5)

In [3]:
print(a)

[ 0.55026189  0.23128546 -2.96220812  1.36127096 -0.17492952]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[ 0.55026189  0.23128546 -2.96220812  1.36127096 -0.17492952]


In [6]:
print(np.dot(a,a.T))

11.014617043037582


In [7]:
a = np.random.randn(5,1)
print(a)

[[-1.34576501]
 [ 0.79639687]
 [-0.50203829]
 [ 0.90216079]
 [-1.4192333 ]]


In [8]:
print(np.dot(a,a.T))

[[ 1.81108347 -1.07176305  0.67562556 -1.21409642  1.90995452]
 [-1.07176305  0.63424798 -0.39982172  0.71847803 -1.13027297]
 [ 0.67562556 -0.39982172  0.25204244 -0.45291925  0.71250945]
 [-1.21409642  0.71847803 -0.45291925  0.81389408 -1.28037663]
 [ 1.90995452 -1.13027297  0.71250945 -1.28037663  2.01422317]]
